default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432


development:
  <<: *default
  database: homework_development
  username: <%= Rails.application.credentials.dig(:development, :database, :user) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
test:
  <<: *default
  database: homework_test
  username: <%= Rails.application.credentials.dig(:test, :database, :user) %>
  password: <%= Rails.application.credentials.dig(:test, :database, :password) %>
